ALTER TABLE user_settings
    ADD COLUMN IF NOT EXISTS auto_qualify BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS auto_draft BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS auto_send BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS auto_send_delay_min INT NOT NULL DEFAULT 5,
    ADD COLUMN IF NOT EXISTS auto_followup BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS auto_followup_days INT NOT NULL DEFAULT 2,
    ADD COLUMN IF NOT EXISTS auto_prospect_to_lead BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS auto_verify_import BOOLEAN NOT NULL DEFAULT false;
