ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS smtp_port VARCHAR(10) NOT NULL DEFAULT '465',
ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255) NOT NULL DEFAULT '';
